version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    container_name: zookeeper
    network_mode: weather_net



  kafka1:
    image: confluentinc/cp-kafka:latest
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      - zookeeper
    ports:
      - "19092:9092"
    container_name: kafka1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    network_mode: weather_net


  kafka2:
    image: confluentinc/cp-kafka:latest
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"
    container_name: kafka2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    network_mode: weather_net


  kafka3:
    image: confluentinc/cp-kafka:latest
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      - zookeeper
    ports:
      - "39092:9092"
    container_name: kafka3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    network_mode: weather_net


  producer:
    image: thescarletarrow/kafka:0.0.26
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - kafka3
      - kafka2
      - kafka1
    network_mode: weather_net
    container_name: producer

  consumer:
    image: thescarletarrow/consumer:0.0.22
    ports:
      - "8080:8080"
    network_mode:  weather_net
    container_name: consumer
    build: .

