#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: spring-kafka:9092
#      auto-offset-reset: earliest
#      group-id: 1
#      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: org.apache.kafka.common.serialization.StringSerializer